url: http://bmuenzenmeyer.github.io
baseurl:
domain: bmuenzenmeyer.github.io
permalink: /:title
name: Brian Muenzenmeyer
description: "The personal site of Brian Muenzenmeyer."
paginate: 10
plugins:
  - jekyll-paginate

exclude:
  - node_modules
  - patternlab-node
