url: http://bmuenzenmeyer.github.io
baseurl:
domain: bmuenzenmeyer.github.io
permalink: /:title
name: Brian Muenzenmeyer
description: 'The personal site of Brian Muenzenmeyer.'
paginate: 10

collections:
  projects:
    output: true

exclude:
- node_modules
- _patternlab

gems: [github-pages, jekyll-paginate]
